import fs from 'node:fs'
import fsp from 'node:fs/promises'
import path from 'node:path'
import crypto from 'node:crypto'
import {
  countRegions,
  migrateProject,
  type Project,
  type ProjectMeta
} from '../../shared/schemas/project'
import type { RecoveryReport, SaveResult } from '../../shared/contracts/ipc'
import { readJson, readJsonWithBackup, writeFileAtomic } from './atomicFile'

/**
 * All project mutations are serialized through this repository's write queue.
 * Deleted project ids are tombstoned so a stale, delayed autosave can never
 * resurrect a deleted project, and revisions are checked so a stale save can
 * never overwrite newer state.
 */
export class ProjectRepository {
  readonly projectsDir: string
  readonly mediaDir: string
  readonly corruptDir: string
  private readonly tombstonePath: string
  private tombstones = new Set<string>()
  private queue: Promise<unknown> = Promise.resolve()
  private recovery: RecoveryReport = { corruptFiles: [] }

  constructor(baseDir: string) {
    this.projectsDir = path.join(baseDir, 'projects')
    this.mediaDir = path.join(baseDir, 'media')
    this.corruptDir = path.join(baseDir, 'corrupt')
    this.tombstonePath = path.join(baseDir, 'tombstones.json')
    fs.mkdirSync(this.projectsDir, { recursive: true })
    fs.mkdirSync(this.mediaDir, { recursive: true })
    this.loadTombstones()
  }

  private loadTombstones() {
    try {
      const raw = JSON.parse(fs.readFileSync(this.tombstonePath, 'utf8'))
      if (Array.isArray(raw)) this.tombstones = new Set(raw.filter((x) => typeof x === 'string'))
    } catch {
      this.tombstones = new Set()
    }
  }

  private enqueue<T>(fn: () => Promise<T>): Promise<T> {
    const next = this.queue.then(fn, fn)
    this.queue = next.catch(() => undefined)
    return next
  }

  private projectPath(id: string): string {
    // Ids are generated by us; still, never allow path traversal.
    if (!/^[a-zA-Z0-9-]+$/.test(id)) throw new Error('Invalid project id')
    return path.join(this.projectsDir, `${id}.json`)
  }

  isDeleted(id: string): boolean {
    return this.tombstones.has(id)
  }

  newId(): string {
    return crypto.randomUUID()
  }

  async recoverProjects(): Promise<RecoveryReport> {
    // Called on startup: quarantine corrupt files (never delete them) and
    // recover from .bak copies where possible.
    return this.enqueue(async () => {
      const files = await fsp.readdir(this.projectsDir)
      for (const file of files) {
        if (!file.endsWith('.json')) continue
        const full = path.join(this.projectsDir, file)
        const { data, usedBackup, corrupt } = await readJsonWithBackup(full)
        if (corrupt) {
          await fsp.mkdir(this.corruptDir, { recursive: true })
          const quarantined = path.join(this.corruptDir, `${file}.${Date.now()}`)
          try {
            await fsp.copyFile(full, quarantined)
          } catch {
            /* keep going; recovery must not destroy other projects */
          }
          this.recovery.corruptFiles.push(file)
          if (data !== null && usedBackup) {
            // Restore the backup as the primary file.
            try {
              await writeFileAtomic(full, JSON.stringify(data, null, 2))
            } catch {
              /* leave the corrupt file in place */
            }
          }
        }
      }
      return this.recovery
    })
  }

  getRecoveryReport(): RecoveryReport {
    return this.recovery
  }

  async listProjects(): Promise<ProjectMeta[]> {
    return this.enqueue(async () => {
      const files = await fsp.readdir(this.projectsDir)
      const metas: ProjectMeta[] = []
      for (const file of files) {
        if (!file.endsWith('.json')) continue
        const id = file.slice(0, -5)
        if (this.tombstones.has(id)) continue
        const raw = await readJson(path.join(this.projectsDir, file))
        if (raw === null) continue // corrupt entries are handled by recoverProjects
        try {
          const project = migrateProject(raw)
          metas.push({
            id: project.id,
            title: project.title,
            pageCount: project.pages.length,
            regionCount: countRegions(project),
            createdAt: project.createdAt,
            updatedAt: project.updatedAt,
            hasThumbnail: fs.existsSync(this.thumbnailPath(project.id))
          })
        } catch {
          continue
        }
      }
      metas.sort((a, b) => b.updatedAt - a.updatedAt)
      return metas
    })
  }

  async getProject(id: string): Promise<Project | null> {
    return this.enqueue(async () => {
      if (this.tombstones.has(id)) return null
      const { data } = await readJsonWithBackup(this.projectPath(id))
      if (data === null) return null
      try {
        return migrateProject(data)
      } catch {
        return null
      }
    })
  }

  async saveProject(project: Project, expectedRevision: number): Promise<SaveResult> {
    return this.enqueue(async () => {
      if (!project || typeof project.id !== 'string') {
        return { ok: false, reason: 'invalid' as const }
      }
      // Rule: never write a deleted project back to disk.
      if (this.tombstones.has(project.id)) {
        return { ok: false, reason: 'deleted' as const }
      }
      const filePath = this.projectPath(project.id)
      const existing = await readJson(filePath)
      const storedRevision =
        existing && typeof existing.revision === 'number' ? existing.revision : 0
      // Rule: a stale delayed save must not overwrite newer state.
      if (existing !== null && storedRevision !== expectedRevision) {
        return { ok: false, reason: 'stale' as const }
      }
      const revision = storedRevision + 1
      const toWrite: Project = { ...project, revision, schemaVersion: 1 }
      try {
        await writeFileAtomic(filePath, JSON.stringify(toWrite, null, 2))
        return { ok: true, revision }
      } catch (err) {
        return { ok: false, reason: 'io-error' as const, message: String(err) }
      }
    })
  }

  async deleteProject(id: string): Promise<boolean> {
    return this.enqueue(async () => {
      // Tombstone first so any in-flight save that lands after this point is rejected.
      this.tombstones.add(id)
      try {
        await writeFileAtomic(this.tombstonePath, JSON.stringify([...this.tombstones]))
      } catch {
        /* tombstone is still held in memory for this session */
      }
      const filePath = this.projectPath(id)
      const project = await readJson(filePath)
      await fsp.rm(filePath, { force: true })
      await fsp.rm(`${filePath}.bak`, { force: true })
      await fsp.rm(this.thumbnailPath(id), { force: true })
      if (project) {
        await this.collectUnusedMedia(project)
      }
      return true
    })
  }

  /** Delete media files that were referenced only by the deleted project. */
  private async collectUnusedMedia(deleted: any): Promise<void> {
    try {
      const deletedRefs = collectMediaRefs(deleted)
      if (deletedRefs.size === 0) return
      const stillUsed = new Set<string>()
      const files = await fsp.readdir(this.projectsDir)
      for (const file of files) {
        if (!file.endsWith('.json')) continue
        const raw = await readJson(path.join(this.projectsDir, file))
        if (raw) for (const ref of collectMediaRefs(raw)) stillUsed.add(ref)
      }
      for (const ref of deletedRefs) {
        if (!stillUsed.has(ref) && /^[a-zA-Z0-9._-]+$/.test(ref)) {
          await fsp.rm(path.join(this.mediaDir, ref), { force: true })
        }
      }
    } catch {
      /* media GC is best-effort */
    }
  }

  async duplicateProject(id: string): Promise<Project | null> {
    const source = await this.getProject(id)
    if (!source) return null
    const now = Date.now()
    // Duplicate with entirely new ids; never reuse deleted or existing ids.
    const copy: Project = {
      ...source,
      id: this.newId(),
      title: `${source.title} copy`,
      createdAt: now,
      updatedAt: now,
      revision: 0,
      pages: source.pages.map((p) => {
        const pageId = crypto.randomUUID()
        return {
          ...p,
          id: pageId,
          placedImages: p.placedImages.map((img) => ({ ...img, id: crypto.randomUUID() })),
          annotations: p.annotations.map((a) => ({ ...a, id: crypto.randomUUID() }))
        }
      })
    }
    copy.activePageId = copy.pages[0]?.id ?? null
    const result = await this.saveProject(copy, 0)
    if (!result.ok) return null
    copy.revision = result.revision!
    return copy
  }

  thumbnailPath(id: string): string {
    return path.join(this.mediaDir, `thumb-${id}.jpg`)
  }

  async saveMediaBuffer(bytes: Buffer, originalName: string): Promise<string> {
    const ext = sanitizeExt(path.extname(originalName)) || '.png'
    const name = `${crypto.randomUUID()}${ext}`
    await fsp.mkdir(this.mediaDir, { recursive: true })
    await fsp.writeFile(path.join(this.mediaDir, name), bytes)
    return name
  }
}

function sanitizeExt(ext: string): string {
  const clean = ext.toLowerCase()
  return ['.png', '.jpg', '.jpeg', '.webp', '.gif', '.bmp', '.avif'].includes(clean) ? clean : ''
}

function collectMediaRefs(project: any): Set<string> {
  const refs = new Set<string>()
  if (!project || !Array.isArray(project.pages)) return refs
  for (const page of project.pages) {
    if (page?.sourceImage?.file) refs.add(String(page.sourceImage.file))
    if (Array.isArray(page?.placedImages)) {
      for (const img of page.placedImages) {
        if (img?.file) refs.add(String(img.file))
      }
    }
  }
  return refs
}
